services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: graphql_api
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb://mongo:27017/graphql-category
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - MAX_CATEGORY_LEVEL=4
    depends_on:
      - mongo
      - redis
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

  mongo:
    image: mongo:8
    container_name: graphql_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine
    container_name: graphql_redis
    ports:
      - "6379:6379"

volumes:
  mongo_data: